### PR TITLE
Use more general regex for numbers to cover coordinates using the scientific notation

### PR DESCRIPTION
**Pull request by lesteve**
Trying to parse this simple [SVG](https://gist.githubusercontent.com/lesteve/d963b88daf162928cafc/raw/5abf902b02c56341567433cdfa1b819047d11b73/line_with_scientific_notation_coordinates.svg), created with Inkscape, raises the following exception `IndexError: pop from empty list`.

This happens because the regex doesn't cover floating point numbers using the scientific notation, e.g. 1.3e-4. From what I understand from http://www.w3.org/TR/SVG/paths.html#PathDataBNF, coordinate using the scientific notation is fine as far as the SVG standard is concerned.

The floating point regex was taken from: https://docs.python.org/2/library/re.html#simulating-scanf. One slight change is that there is no space allowed between the potential sign and the next digit. The thing is that the float function is applied to the matches in some of the code, and that would fail if there was a space.

Also I reused the `number_re` regexp in a couple of other places which seemed like they were trying to find a number.

### CODE REVIEW

**Comment by lesteve** [comment]
Somehow I managed to miss the fact that #4 was a report of exactly the same issue.

**Comment by lesteve** [comment]
@cjlano any reason not to merge this pull request? It seems like a reasonable, albeit tiny enhancement.

**Comment by cjlano** [comment]
Hello @lesteve 
Sorry for the delayed answer, but as mentioned in #4, this bug is broader than just scientific notation.
While your pull request is totally valid, I'd like to fix the issue using a complete SVG grammar parser. This is a lot of work, and help is welcome.

**Comment by lesteve** [comment]
I agree that the pyparsing option is probably the right way to do it in the long term.

In my mind, this PR is just a stop-gap solution that fixes a existing short-coming. It don't think it impedes in any way using a complete SVG grammar in the long run.

Some more background about my use case: I have an SVG which contains only Bézier curves and segments, I want to extract the point coordinates to be able to draw it using matplotlib. Except for this tiny bug, your parser fit exactly the job I needed it for, so thanks for that!

**Comment by cjlano** [comment]
OK, merged. Thank you!
I slightly edited your commit for coding style.

Thanks for your contribution and sorry for the delay. Hopefully we will have soon a better parser for Path data.

**Comment by lesteve** [comment]
Great, thanks a lot!

**Comment by wolfv** [comment]
cool :+1:

**Pull request closed without merging**
